# Generated by Django 5.2.4 on 2025-07-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='success_rate',
            field=models.FloatField(default=1),
        ),
    ]
